name = "Lgmsh"
uuid = "901517f6-ef86-4a80-bf35-2c5b8e720204"
authors = ["Eduardo Lenz <eduardobarplenz@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
